package q;
import c.*;

/* this creates an int representation based on the Kociemba subset, just like the above subsets
 * the (kernel of the) Kociemba coordinate is generated by <U, R2, D>, or can be considered to be all CO & EO oriented,
 * with all midlayer edges on the midlayer. I relied on Kociemba's definition of the midlayer slice. */

public class Kociemba extends MultiCoordinate {
    private static String NAME;
    static {
        NAME = "Kociemba";
    }
    public Kociemba(Cube cube) {
        super();
        super.name = NAME;
        addCoordinate(new CO(cube));
        addCoordinate(new EO(cube));
        addCoordinate(new UDSlice(cube));
    }
    public Kociemba() {
        super();
        super.name = NAME;
        addCoordinate(new CO());
        addCoordinate(new EO());
        addCoordinate(new UDSlice());
    }
    
    public String name() {return NAME;}
}